
"use client"

import Head from "next/head";
import { Scanner } from "@yudiel/react-qr-scanner";
import { useCallback, useState } from "react";
import DialogComponent from "~/components/dialogComponent";

export default function Home() {
  const [qrValue, setQrValue] = useState<string | undefined>();

  const onQaSuccess = useCallback(
    (rawValue: string) => {
      setQrValue(rawValue);
    },
    [setQrValue],
  );

  console.log(qrValue);

  return (
    <>
      <Head>
        <title>QR Scanner - POC</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            QR Scanner
          </h1>
          <div className="flex text-center">
            <Scanner
              onScan={(result) => onQaSuccess(result[0]?.rawValue ?? "NA")}
              
            />
            ;
          </div>
        </div>
        <DialogComponent
          isOpen={qrValue !== undefined}
          message={`Valor: ${qrValue}`}
          onClose={() => setQrValue(undefined)}
          title="QR Code Encontrado!"
        />
      </main>
    </>
  );
}
